[package]
name = "vtsampler"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "25.0.2"
smallvec = "1.15.1"

[dev-dependencies]
winit = "0.30.11"
anyhow = "1.0.98"
pollster = "0.4"
bytemuck = { version = "1.17", features = ["derive"] }
